3.3.49

diff --git a/varmyknife b/varmyknife
--- a/varmyknife
+++ b/varmyknife
@@ -22,6 +22,13 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
 
 VARMYKNIFE_JAR=${DIR}/../vArmyKnife.jar
 
+if [ ! -f "${VARMYKNIFE_JAR}" ]; then
+  VARMYKNIFE_JAR=${DIR}/vArmyKnife.jar
+fi
+if [ ! -f "${VARMYKNIFE_JAR}" ]; then
+  (>&2 echo "ERROR: CANNOT FIND VARMYKNIFE_JAR")
+fi
+
 (>&2 echo "JAVA=${WHICH_JAVA}")
 (>&2 echo "JAR=${VARMYKNIFE_JAR}")
 
